aquavm_pool_size = 2
tcp_port = 7_771
websocket_port = 9_991
http_port = 18_080

[system_services]
enable = [ "aqua-ipfs", "decider" ]

  [system_services.aqua_ipfs]
  external_api_multiaddr = "/ip4/127.0.0.1/tcp/5001"
  local_api_multiaddr = "/dns4/ipfs/tcp/5001"

  [system_services.decider]
  decider_period_sec = 10
  worker_ipfs_multiaddr = "/dns4/ipfs/tcp/5001"
  network_api_endpoint = "http://chain-rpc:8545"
  network_id = 31_337
  start_block = "earliest"
  matcher_address = "0x68B1D87F95878fE05B998F19b66F4baba5De1aed"
  wallet_key = "0xe6771e3e60ec7e3db04c282531c0eee8008c928aa17f937682b06e29fd6984ea"

[chain_config]
http_endpoint = "http://chain-rpc:8545"
core_contract_address = "0x0B306BF915C4d645ff596e518fAf3F9669b97016"
cc_contract_address = "0x3Aa5ebB10DC797CAC828524e59A333d0A371443c"
market_contract_address = "0x68B1D87F95878fE05B998F19b66F4baba5De1aed"
network_id = 31_337
wallet_key = "0xe6771e3e60ec7e3db04c282531c0eee8008c928aa17f937682b06e29fd6984ea"
