# yaml-language-server: $schema=schemas/docker-compose.json

# Defines a multi-containers based application.

# Documentation: https://github.com/fluencelabs/cli/tree/main/docs/configs/docker-compose.md

version: "3"

volumes:
  ipfs: null
  postgres: null
  nox-0: null
  nox-1: null
  nox-2: null

secrets:
  nox-0:
    file: secrets/nox-0.txt
  nox-1:
    file: secrets/nox-1.txt
  nox-2:
    file: secrets/nox-2.txt

services:
  ipfs:
    image: ipfs/kubo
    ports:
      - 5001:5001
      - 4001:4001
    environment:
      IPFS_PROFILE: server
    volumes:
      - ipfs:/data/ipfs
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    command:
      - postgres
      - -cshared_preload_libraries=pg_stat_statements
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      PGDATA: /var/lib/postgresql/data
      POSTGRES_INITDB_ARGS: -E UTF8 --locale=C
    volumes:
      - postgres:/var/lib/postgresql/data
  chain-rpc:
    image: docker.fluence.dev/chain-rpc:main-d95d05b-219-1
    ports:
      - 8545:8545
  chain-deploy-script:
    image: docker.fluence.dev/chain-deploy-script:main-d95d05b-219-1
    environment:
      CHAIN_RPC_URL: http://chain-rpc:8545
      MAX_FAILED_RATIO: "9999"
      IS_MOCKED_RANDOMX: "true"
    depends_on:
      - chain-rpc
  graph-node:
    image: graphprotocol/graph-node:v0.33.0
    ports:
      - 8000:8000
      - 8001:8001
      - 8020:8020
      - 8030:8030
      - 8040:8040
    depends_on:
      - ipfs
      - postgres
      - chain-rpc
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: ipfs:5001
      ethereum: local:http://chain-rpc:8545
      GRAPH_LOG: info
      ETHEREUM_REORG_THRESHOLD: 1
      ETHEREUM_ANCESTOR_COUNT: 1
  subgraph-deploy-script:
    image: docker.fluence.dev/subgraph-deploy-script-image:main-d95d05b-219-1
    environment:
      GRAPHNODE_URL: http://graph-node:8020
      IPFS_URL: http://ipfs:5001
    depends_on:
      - graph-node
  nox-0:
    image: fluencelabs/nox:0.20.0
    ports:
      - 7771:7771
      - 9991:9991
    environment:
      WASM_LOG: info
      FLUENCE_MAX_SPELL_PARTICLE_TTL: 9s
      FLUENCE_ROOT_KEY_PAIR__PATH: /run/secrets/nox-0
      RUST_LOG: run-console=trace,aquamarine::log=debug,network=trace,worker_inactive=trace
    command:
      - --config=/run/configs/nox-0_Config.toml
      - --external-maddrs
      - /dns4/nox-0/tcp/7771
      - /dns4/nox-0/tcp/9991/ws
      - --allow-private-ips
      - --local
    depends_on:
      - ipfs
      - chain-rpc
      - chain-deploy-script
    volumes:
      - ./configs/nox-0_Config.toml:/run/configs/nox-0_Config.toml
      - nox-0:/.fluence
    secrets:
      - nox-0
  nox-1:
    image: fluencelabs/nox:0.20.0
    ports:
      - 7772:7772
      - 9992:9992
    environment:
      WASM_LOG: info
      FLUENCE_MAX_SPELL_PARTICLE_TTL: 9s
      FLUENCE_ROOT_KEY_PAIR__PATH: /run/secrets/nox-1
      RUST_LOG: run-console=trace,aquamarine::log=debug,network=trace,worker_inactive=trace
    command:
      - --config=/run/configs/nox-1_Config.toml
      - --external-maddrs
      - /dns4/nox-1/tcp/7772
      - /dns4/nox-1/tcp/9992/ws
      - --allow-private-ips
      - --bootstraps=/dns/nox-0/tcp/7771
    depends_on:
      - ipfs
      - chain-rpc
      - chain-deploy-script
    volumes:
      - ./configs/nox-1_Config.toml:/run/configs/nox-1_Config.toml
      - nox-1:/.fluence
    secrets:
      - nox-1
  nox-2:
    image: fluencelabs/nox:0.20.0
    ports:
      - 7773:7773
      - 9993:9993
    environment:
      WASM_LOG: info
      FLUENCE_MAX_SPELL_PARTICLE_TTL: 9s
      FLUENCE_ROOT_KEY_PAIR__PATH: /run/secrets/nox-2
      RUST_LOG: run-console=trace,aquamarine::log=debug,network=trace,worker_inactive=trace
    command:
      - --config=/run/configs/nox-2_Config.toml
      - --external-maddrs
      - /dns4/nox-2/tcp/7773
      - /dns4/nox-2/tcp/9993/ws
      - --allow-private-ips
      - --bootstraps=/dns/nox-0/tcp/7771
    depends_on:
      - ipfs
      - chain-rpc
      - chain-deploy-script
    volumes:
      - ./configs/nox-2_Config.toml:/run/configs/nox-2_Config.toml
      - nox-2:/.fluence
    secrets:
      - nox-2
