[package]
name = "myService"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "myService"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.10.1"

[dev-dependencies]
marine-rs-sdk-test = "0.12.0"
