name: "ci"

on:
  pull_request:
  push:
    branches:
      - "main"

env:
  FORCE_COLOR: true

jobs:
  check-compiles:
    name: "Check Aqua compiles"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Setup fcli
        uses: fluencelabs/setup-fluence@v1
        with:
          artifact: fcli
          version: unstable

      - run: npm i

      - name: Check compilation
        run: npm run compile-dry